/* Auto-generated inline Quick Insights (3JN) */
(function(){
  window.GoMissionQuickInsightsInline = window.GoMissionQuickInsightsInline || {};
  window.GoMissionQuickInsightsInline['3JN'] = {
  "id": "3JN",
  "name": "3 John",
  "type": "quick-insights-gpt5-mini-commentary-hybrid",
  "generatedAt": "2026-01-26T09:20:40.913Z",
  "chapters": {
    "1": {
      "verses": {
        "1": {
          "en": {
            "understanding": "In this verse, we see a letter from John, who is referred to as 'the elder.' This shows that John is writing with authority and experience, likely to provide guidance and encouragement to the recipient. The letter is addressed to Gaius, a name that was common in the New Testament, indicating that there were several people with this name. However, John expresses a personal affection for this particular Gaius, calling him 'beloved.' This shows the close relationship and the deep respect John has for him. The use of 'in the truth' highlights the importance of genuine faith and relationship in the Christian community, emphasizing that love should be rooted in truth and faithfulness.",
            "livingItOut": "To live out this verse, think about the people in your life that you hold dear, just like John cherished Gaius. Take a moment today to reach out to someone you love—maybe send them a message or give them a call to express your appreciation. In Filipino culture, we value relationships and connections, so sharing your feelings can strengthen your bond. Additionally, consider how you can be a source of truth and love in your community. Perhaps you can volunteer at your local church or help a neighbor in need. Small acts of kindness rooted in love and truth can make a big difference in the lives of those around you.",
            "godsLove": "This verse beautifully reflects God's love for us through the relationship between John and Gaius. Just as John expresses his love and respect for Gaius, God loves each of us deeply and personally. He knows us by name and cherishes us for who we are. God's love is not just a feeling; it’s an action that encourages us to live in truth and community. When you face challenges, remember that you are beloved by God, and He desires for you to experience genuine relationships filled with truth and love. You are never alone, and His love will always support you through every situation.",
            "reflection": "Who are the people in your life that you can express love and appreciation to today?"
          },
          "tl": {
            "understanding": "Sa talatang ito, makikita natin ang isang liham mula kay Juan, na tinatawag na 'ang matanda.' Ipinapakita nito na si Juan ay sumusulat nang may awtoridad at karanasan, marahil upang magbigay ng gabay at pahalagahan sa tumanggap. Ang liham ay nakalaan kay Gaius, isang pangalang karaniwan sa Bagong Tipan, na nagpapahiwatig na maraming tao ang may pangalang ito. Ngunit, ipinapakita ni Juan ang kanyang personal na pagmamahal para sa partikular na Gaius na ito, tinatawag siyang 'minamahal.' Ipinapakita nito ang malapit na ugnayan at ang malalim na paggalang ni Juan sa kanya. Ang paggamit ng 'sa katotohanan' ay nagbibigay-diin sa kahalagahan ng tunay na pananampalataya at relasyon sa komunidad ng mga Kristiyano, na ang pagmamahal ay dapat nakaugat sa katotohanan at katapatan.",
            "livingItOut": "Para maisagawa ang talatang ito, isipin mo ang mga tao sa buhay mo na mahalaga sa iyo, gaya ng pagmamahal ni Juan kay Gaius. Maglaan ka ng oras ngayon para makipag-ugnayan sa isang taong mahal mo—maaaring magpadala ka ng mensahe o tumawag upang ipahayag ang iyong pagpapahalaga. Sa kulturang Pilipino, mahalaga ang mga relasyon, kaya ang pagbabahagi ng iyong nararamdaman ay makakapagpatibay ng inyong ugnayan. Isipin din kung paano ka magiging pinagmumulan ng katotohanan at pagmamahal sa iyong komunidad. Baka puwede kang magboluntaryo sa iyong lokal na simbahan o tumulong sa kapitbahay na nangangailangan. Ang maliliit na gawa ng kabaitan na nakaugat sa pagmamahal at katotohanan ay makakagawa ng malaking pagkakaiba sa buhay ng mga tao sa paligid mo.",
            "godsLove": "Ang talatang ito ay maganda at nagpapakita ng pagmamahal ng Diyos sa atin sa pamamagitan ng ugnayan nina Juan at Gaius. Gaya ng ipinapahayag ni Juan ang kanyang pagmamahal at paggalang kay Gaius, ganun din ang pagmamahal ng Diyos sa bawat isa sa atin. Kilala Niya tayo sa pangalan at pinahahalagahan tayo sa kung sino tayo. Ang pagmamahal ng Diyos ay hindi lamang isang pakiramdam; ito ay isang aksyon na nag-uudyok sa atin na mamuhay sa katotohanan at komunidad. Kapag nasa gitna ka ng mga pagsubok, alalahanin mong ikaw ay minamahal ng Diyos, at nais Niyang maranasan mo ang tunay na relasyon na puno ng katotohanan at pagmamahal. Hindi ka nag-iisa, at ang Kanyang pagmamahal ay laging susuporta sa iyo sa bawat sitwasyon.",
            "reflection": "Sino-sino ang mga tao sa buhay mo na maaari mong ipahayag ang pagmamahal at pagpapahalaga sa kanila ngayon?"
          }
        },
        "2": {
          "en": {
            "understanding": "In this verse, John is expressing his heartfelt desire for the well-being of the person he loves. He is praying for them to prosper in every aspect of their life, including their health and finances, just as their soul is thriving in their relationship with God. This shows that John understands the importance of holistic well-being—it's not just about spiritual health but also about physical and emotional prosperity. In the early church, many faced struggles and persecution, so this prayer is a reminder of the hope and blessings that God desires for us in our daily lives. It emphasizes that our spiritual growth can positively influence our overall well-being.",
            "livingItOut": "To live out this verse, start by checking in on your health and well-being. Are you taking care of your physical body? Consider incorporating healthier meals or regular exercise into your routine. You might also want to reach out to friends or family members to encourage them and uplift their spirits. Share a meal, pray together, or just spend quality time, which can help both you and them prosper emotionally. Furthermore, remember to nurture your spiritual life—read the Bible, pray daily, and seek God’s guidance. By focusing on all areas of life, you can experience the fullness of joy that God promises.",
            "godsLove": "This verse beautifully shows how much God cares for us in every part of our lives. It’s like a loving parent who wants nothing but the best for their child. God desires for us to not only grow spiritually but also to experience joy and health in our daily living. When we face challenges, whether in our health or finances, we can lean on Him, knowing He wants us to thrive. His love is not limited to our spiritual journey; it encompasses our entire existence. God wants us to feel His presence in both our struggles and victories, assuring us that He is always there to support us.",
            "reflection": "In what areas of your life do you feel you need God's blessing and prosperity right now?"
          },
          "tl": {
            "understanding": "Sa talatang ito, ipinapahayag ni Juan ang taos-pusong pagnanais niya para sa kabutihan ng taong mahal niya. Ipinapanalangin niya na magtagumpay sila sa lahat ng aspeto ng kanilang buhay, kasama na ang kalusugan at pananalapi, gaya ng pagyabong ng kanilang kaluluwa sa relasyon nila sa Diyos. Ipinapakita nito na nauunawaan ni Juan ang kahalagahan ng kabuuang kalusugan—hindi lang ito tungkol sa espiritwal na kalusugan kundi pati na rin sa pisikal at emosyonal na kasaganaan. Sa mga unang simbahan, marami ang humaharap sa mga pagsubok at pag-uusig, kaya't ang panalangin na ito ay paalala ng pag-asa at mga biyayang nais ng Diyos para sa atin sa ating pang-araw-araw na buhay. Binibigyang-diin nito na ang ating espiritwal na pag-unlad ay maaaring makapagpabuti sa ating kabuuang kalagayan.",
            "livingItOut": "Para maisakatuparan ang talatang ito, magsimula sa pag-check kung paano mo pinapangalagaan ang iyong kalusugan at kapakanan. Inaalagaan mo ba ang iyong pisikal na katawan? Isaalang-alang ang pagdagdag ng mas masustansyang pagkain o regular na ehersisyo sa iyong gawain. Maaari mo ring tawagan ang mga kaibigan o pamilya para magbigay ng suporta at mag uplift ng kanilang spirito. Mag-share ng pagkain, magdasal nang magkasama, o maglaan ng oras, na makakatulong sa inyong dalawa upang umunlad sa emosyonal. Bukod dito, huwag kalimutang alagaan ang iyong espiritwal na buhay—magbasa ng Bibliya, manalangin araw-araw, at humingi ng gabay sa Diyos. Sa pamamagitan ng pagtutok sa lahat ng aspeto ng buhay, mararanasan mo ang kasaganaan ng kagalakan na ipinapangako ng Diyos.",
            "godsLove": "Ang talatang ito ay maganda ang nagpapakita kung gaano tayo kamahal ng Diyos sa bawat bahagi ng ating buhay. Para itong mapagmahal na magulang na walang ibang hangad kundi ang kabutihan ng kanilang anak. Nais ng Diyos na hindi lang tayo lumago sa espiritwal kundi maranasan din ang saya at kalusugan sa ating pang-araw-araw na pamumuhay. Kapag tayo ay humaharap sa mga hamon, sa kalusugan man o sa pananalapi, maaari tayong kumapit sa Kanya, alam na nais Niyang tayo ay umunlad. Ang Kanyang pag-ibig ay hindi limitado sa ating espiritwal na paglalakbay; ito ay sumasaklaw sa ating buong pag-iral. Nais ng Diyos na maramdaman natin ang Kanyang presensya sa parehong ating mga pakik struggles at tagumpay, na nagsisiguro sa atin na lagi siyang nandiyan upang suportahan tayo.",
            "reflection": "Sa anong bahagi ng iyong buhay mo nararamdaman na kailangan mo ng biyaya at kasaganaan mula sa Diyos ngayon?"
          }
        },
        "3": {
          "en": {
            "understanding": "In this verse, John expresses his joy upon hearing from the traveling teachers, who are likely his friends and fellow believers. They shared how Gaius, a member of their community, remains committed to living out the truth of the Gospel. This was especially important because there were false teachers spreading lies about Jesus, denying His humanity and sacrifice. John is celebrating Gaius's faithfulness to the true message of Jesus, which emphasizes living in accordance with God's truth. This verse highlights the importance of staying grounded in our faith and supporting one another in our Christian walk.",
            "livingItOut": "To apply this verse in our daily lives, we can take time to encourage and support our friends and family in their faith journeys. Perhaps you can reach out to someone who has been struggling and remind them of God’s truth and love. You can also seek out opportunities to learn more about the Bible, just like Gaius did, by joining a Bible study group or attending church regularly. Additionally, sharing your own experiences of faith with others can inspire them and create a supportive community. Small acts of encouragement can go a long way in helping others walk in truth.",
            "godsLove": "This verse beautifully showcases God's love for us through the encouragement we receive from fellow believers. Just like John was filled with joy when he heard about Gaius's faithfulness, God delights in seeing us walk in truth and love. It reminds us that we are not alone in our journey; God has placed people around us to lift us up and guide us. Even when we face challenges or doubts, know that God cares deeply for you and celebrates every step you take toward Him. His grace is sufficient, and His love surrounds you, encouraging you to keep moving forward.",
            "reflection": "How can you encourage someone in your life to stay true to their faith this week?"
          },
          "tl": {
            "understanding": "Sa talatang ito, ipinahayag ni Juan ang kanyang kagalakan nang marinig mula sa mga naglalakbay na guro, na malamang ay kanyang mga kaibigan at kapwa mananampalataya. Ibinahagi nila kung paano si Gaius, isang miyembro ng kanilang komunidad, ay patuloy na tapat sa pamumuhay ayon sa katotohanan ng Ebanghelyo. Mahalaga ito dahil may mga huwad na guro na nagkalat ng mga kasinungalingan tungkol kay Jesus, na tinatanggihan ang Kanyang pagkatao at sakripisyo. Ipinagdiriwang ni Juan ang katapatan ni Gaius sa tunay na mensahe ni Jesus, na nagtatampok sa kahalagahan ng pananatiling nakatayo sa ating pananampalataya at pagtulong sa isa’t isa sa ating paglalakbay bilang mga Kristiyano.",
            "livingItOut": "Para maisagawa ang talatang ito sa ating pang-araw-araw na buhay, maaari tayong maglaan ng oras upang hikayatin at suportahan ang ating mga kaibigan at pamilya sa kanilang mga pananampalataya. Maaaring mag-reach out ka sa isang tao na nahihirapan at ipaalala sa kanya ang katotohanan at pagmamahal ng Diyos. Maaari ka ring maghanap ng mga pagkakataon upang matuto pa tungkol sa Biblia, tulad ng ginawa ni Gaius, sa pamamagitan ng pagsali sa isang Bible study group o pagdalo sa simbahan nang regular. Bukod dito, ang pagbabahagi ng iyong sariling karanasan ng pananampalataya sa iba ay makakapagbigay inspirasyon sa kanila at makakatawid ng suportadong komunidad. Ang maliliit na hakbang ng pag-hikbi ay maaaring magdala ng malaking tulong sa iba upang manatiling tapat sa katotohanan.",
            "godsLove": "Ang talatang ito ay magandang pagpapakita ng pagmamahal ng Diyos sa atin sa pamamagitan ng suporta na natatanggap natin mula sa mga kapwa mananampalataya. Katulad ng kagalakan ni Juan nang marinig niya ang tungkol sa katapatan ni Gaius, natutuwa ang Diyos na makita tayong namumuhay sa katotohanan at pagmamahal. Ipinapaalala nito sa atin na hindi tayo nag-iisa sa ating paglalakbay; inilagay ng Diyos ang mga tao sa paligid natin upang tayo ay iangat at gabayan. Kahit sa mga pagsubok o pagdududa, alamin mong ang Diyos ay may malalim na pag-aalaga para sa iyo at ipinagdiriwang ang bawat hakbang na iyong ginagawa patungo sa Kanya. Sapat ang Kanyang biyaya, at ang Kanyang pagmamahal ay nakapaligid sa iyo, hinihikayat kang patuloy na umusad.",
            "reflection": "Paano mo maihihikayat ang isang tao sa iyong buhay na manatiling tapat sa kanilang pananampalataya sa linggong ito?"
          }
        },
        "4": {
          "en": {
            "understanding": "In this verse, John expresses his deep joy when he hears that his spiritual children are living according to the truth. This truth refers to the teachings of Jesus and the way of life that aligns with it. John contrasts the faithfulness of these believers with others like Diotrephes, who did not support the truth and led others away from it. John’s joy comes from knowing that the people he cares about are embracing the right path in their lives. It highlights the importance of walking in truth, which means living out our faith in daily actions and choices. Essentially, John is celebrating their commitment to living as Jesus taught.",
            "livingItOut": "To live out this verse, think about the people in your life whom you can encourage to walk in the truth. Perhaps you can reach out to a friend or a family member and share a Bible verse or a personal testimony about how God has worked in your life. You can also create a small group for Bible study or prayer to help each other grow in faith. Another practical step is to examine your own life: are your actions reflecting the truth you believe? Take time today to reflect on your daily choices and consider how you can align them more closely with God's teachings. This can be as simple as showing kindness to someone in need or being honest in your work.",
            "godsLove": "This verse shows how deeply God cares for us, just like a loving parent who takes joy in their children's growth and well-being. When we walk in truth, it brings Him great joy because it means we are living in harmony with His will. God’s love is evident in the way He guides us towards what is good and true. He desires for us to experience the fullness of life that comes from following Him. Even in our struggles, when we choose to walk in truth, we can feel His presence and support. Remember, God is cheering for you as you take steps toward His truth and live in a way that honors Him.",
            "reflection": "How can you encourage someone in your life to walk in truth today?"
          },
          "tl": {
            "understanding": "Sa talatang ito, ipinahayag ni Juan ang kanyang labis na kaligayahan nang marinig niyang ang kanyang mga espirituwal na anak ay namumuhay ayon sa katotohanan. Ang katotohanang ito ay tumutukoy sa mga turo ni Hesus at sa paraan ng pamumuhay na nakahanay dito. Kinatastasan ni Juan ang katapatan ng mga mananampalataya na ito sa iba tulad ni Diotrephes, na hindi sumusuporta sa katotohanan at nag-udyok sa iba na lumihis mula dito. Ang kaligayahan ni Juan ay nagmumula sa kaalaman na ang mga tao na kanyang pinahahalagahan ay niyayakap ang tamang landas sa kanilang buhay. Ipinapakita nito ang kahalagahan ng pamumuhay sa katotohanan, na nangangahulugang ipinamumuhay ang ating pananampalataya sa mga araw-araw na aksyon at desisyon. Sa madaling salita, ipinagdiriwang ni Juan ang kanilang pangako na mamuhay ayon sa mga turo ni Hesus.",
            "livingItOut": "Para maisakatuparan ang talatang ito, isipin mo ang mga tao sa iyong buhay na maaari mong hikayatin na mamuhay sa katotohanan. Maaaring makipag-ugnayan ka sa isang kaibigan o kapamilya at ibahagi ang isang talata mula sa Bibliya o isang personal na patotoo kung paano kumilos ang Diyos sa iyong buhay. Maaari ka ring lumikha ng maliit na grupo para sa pag-aaral ng Bibliya o panalangin upang matulungan ang bawat isa na lumago sa pananampalataya. Isang praktikal na hakbang ay suriin ang iyong sariling buhay: ang iyong mga aksyon ba ay nagpapakita ng katotohanang iyong pinaniniwalaan? Maglaan ng oras ngayon upang magmuni-muni sa iyong mga desisyon sa araw-araw at isaalang-alang kung paano mo mas maiuugnay ang mga ito sa mga turo ng Diyos. Maaaring kasing simple ito ng pagpapakita ng kabaitan sa isang tao sa pangangailangan o pagiging tapat sa iyong trabaho.",
            "godsLove": "Ipinapakita ng talatang ito kung gaano kalalim ang pagm caring ng Diyos para sa atin, katulad ng isang mapagmahal na magulang na nagagalak sa paglago at kapakanan ng kanilang mga anak. Kapag tayo ay namumuhay sa katotohanan, nagdudulot ito sa Kanya ng malaking kaligayahan dahil nangangahulugan ito na tayo ay namumuhay ayon sa Kanyang kalooban. Ang pagmamahal ng Diyos ay makikita sa paraan ng Kanyang paggabay sa atin patungo sa mabuti at totoo. Nais Niya tayong maranasan ang kabuuan ng buhay na nagmumula sa pagsunod sa Kanya. Kahit sa ating mga pagsubok, kapag pinili nating lumakad sa katotohanan, mararamdaman natin ang Kanyang presensya at suporta. Tandaan, ang Diyos ay sumusuporta sa iyo habang ikaw ay humahakbang patungo sa Kanyang katotohanan at namumuhay sa paraang nagbibigay ng karangalan sa Kanya.",
            "reflection": "Paano mo mahihikayat ang isang tao sa iyong buhay na mamuhay sa katotohanan ngayon?"
          }
        },
        "5": {
          "en": {
            "understanding": "In this verse, John is writing to Gaius, a believer who has been very kind and generous to other Christians, especially those he doesn't know personally. These travelers are teachers sent by John to spread the message of Christ. By welcoming and caring for them, Gaius demonstrates his faithfulness to God. This shows us that our actions towards others, even strangers, reflect our commitment to our faith. Gaius' hospitality was a way to support the spreading of the Gospel and to live out the teachings he had received from the apostles.",
            "livingItOut": "You can live out this verse by showing kindness and hospitality to those around you, especially to people who might need a helping hand. For example, you could invite a new neighbor over for a meal or offer to help someone in your community who is struggling. Even small gestures, like sharing a meal or offering your time, can make a big difference. Think about how you can support others in your church or community, whether it’s through volunteering, donating, or simply checking in on someone who might be feeling alone. Your actions, no matter how small, reflect your love for God and for others.",
            "godsLove": "This verse beautifully shows how God loves us and encourages us to love one another. Just like Gaius opened his home and heart to strangers, God invites us to do the same. His care for us is reflected in how we treat others, reminding us that we are all part of one big family. God sees our efforts to help others, and He is pleased when we act out of love and kindness. So, when you reach out to someone in need, remember that you're showing God's love in action. He’s proud of you for being faithful and generous, just like Gaius.",
            "reflection": "In what ways can you show kindness to someone who is a stranger to you today?"
          },
          "tl": {
            "understanding": "Sa talatang ito, sinusulatan ni Juan si Gaius, isang mananampalataya na napakabait at mapagbigay sa ibang mga Kristiyano, lalo na sa mga hindi niya kilala. Ang mga manlalakbay na ito ay mga guro na ipinadala ni Juan upang ipalaganap ang mensahe ni Cristo. Sa pagtanggap at pag-aalaga kay Gaius sa kanila, ipinapakita niya ang kanyang katapatan sa Diyos. Ipinapakita nito sa atin na ang ating mga gawa para sa iba, kahit pa sa mga estranghero, ay nagsasalamin ng ating pananampalataya. Ang pagkamapagpatuloy ni Gaius ay isang paraan upang suportahan ang pagpapalaganap ng Ebanghelyo at isabuhay ang mga turo na natanggap niya mula sa mga apostol.",
            "livingItOut": "Maaari mong isabuhay ang talatang ito sa pamamagitan ng pagpapakita ng kabaitan at pagkamapagpatuloy sa mga tao sa paligid mo, lalo na sa mga nangangailangan. Halimbawa, maaari mong anyayahan ang bagong kapitbahay na kumain sa iyong bahay o tumulong sa isang taong nahihirapan sa iyong komunidad. Kahit na maliit na mga gawain, tulad ng pagbabahagi ng pagkain o pagbibigay ng oras, ay maaaring magdulot ng malaking pagbabago. Isipin kung paano ka makakatulong sa iba sa iyong simbahan o komunidad, maaaring sa pamamagitan ng volunteering, pagdo-donate, o simpleng pag-check in sa isang tao na maaaring nag-iisa. Ang iyong mga aksyon, kahit gaano kaliit, ay nagsasalamin ng iyong pagmamahal sa Diyos at sa kapwa.",
            "godsLove": "Ang talatang ito ay maganda ang pagpapakita kung paano tayo mahal ng Diyos at hinihikayat tayong mahalin ang isa’t isa. Gaya ng ginawa ni Gaius na binuksan ang kanyang tahanan at puso sa mga estranghero, inaanyayahan tayo ng Diyos na gawin din ito. Ang Kanyang pag-aalaga sa atin ay naipapakita sa kung paano natin tratuhin ang iba, na nagpapaalala sa atin na tayo ay bahagi ng isang malaking pamilya. Nakikita ng Diyos ang ating mga pagsisikap na tumulong sa iba, at nalulugod Siya kapag tayo ay kumikilos mula sa pagmamahal at kabaitan. Kaya, kapag ikaw ay umabot sa isang tao sa pangangailangan, alalahanin mong ipinapakita mo ang pagmamahal ng Diyos sa pagkilos. Ipinagmamalaki ka Niya sa iyong katapatan at pagiging mapagbigay, tulad ni Gaius.",
            "reflection": "Sa anong paraan mo maipapakita ang kabaitan sa isang estranghero ngayon?"
          }
        },
        "6": {
          "en": {
            "understanding": "In this verse, John is writing to a church, likely in Ephesus, where he was living at the time. Ephesus was a bustling city, known for its trade and as a center for the early Christian community. John is encouraging the church to support fellow believers who have shared news about their love. This verse highlights the importance of showing hospitality and kindness to those who serve God. By sending these messengers on their way in a way that honors God, the church demonstrates its love and commitment to the mission of sharing the Gospel. It’s a reminder that our actions towards others reflect our faith and love for God.",
            "livingItOut": "To live out this verse today, think about how you can support those around you, especially those who are serving in ministry or helping others. You can start by offering a helping hand to someone in your community, whether it’s volunteering your time, sharing resources, or simply encouraging them with kind words. For instance, if you know someone who's starting a new project for their church, consider giving them a small gift to show your support or help them spread the word. You can also pray for those who are in ministry, asking God to bless their efforts. Remember, even small gestures can have a big impact!",
            "godsLove": "This verse beautifully illustrates how God wants us to care for one another. When John talks about sending others on their way in a manner worthy of God, it shows that God values our relationships and the way we treat each other. God loves us deeply and encourages us to reflect that love in our actions. He wants us to be generous, kind, and supportive, especially to those who are working hard in His name. In our everyday struggles, we can find comfort in knowing that God is cheering us on and wants us to extend that same support to others. His love empowers us to be a blessing!",
            "reflection": "How can you show love and support to someone in your life who is serving God or your community this week?"
          },
          "tl": {
            "understanding": "Sa talatang ito, sumusulat si Juan sa isang simbahan, na malamang ay nasa Efeso, kung saan siya nananatili noon. Ang Efeso ay isang masiglang lungsod, kilala sa kalakalan at bilang sentro ng maagang komunidad ng Kristiyano. Hinihimok ni Juan ang simbahan na suportahan ang mga kapwa mananampalataya na nagdala ng balita tungkol sa kanilang pagmamahal. Ipinapakita ng talatang ito ang kahalagahan ng pagpapakita ng kabutihan at pagtanggap sa mga nagsisilbi sa Diyos. Sa pagpapadala sa mga mensahero sa paraang karapat-dapat kay Diyos, ipinapakita ng simbahan ang kanilang pagmamahal at dedikasyon sa misyon ng pagbabahagi ng Ebanghelyo. Isang paalala ito na ang ating mga kilos patungo sa iba ay nagrereflect ng ating pananampalataya at pagmamahal kay Diyos.",
            "livingItOut": "Para maisagawa ang talatang ito sa araw-araw, isipin mo kung paano mo masusuportahan ang mga tao sa paligid mo, lalo na ang mga nagsisilbi sa ministeryo o tumutulong sa iba. Maaari kang magsimula sa pamamagitan ng pagbibigay ng tulong sa iyong komunidad, kahit sa simpleng paraan tulad ng pag-volunteer ng iyong oras, pagbabahagi ng mga yaman, o kahit pagpapalakas ng loob sa pamamagitan ng magagandang salita. Halimbawa, kung may kilala kang nag-uumpisang proyekto para sa kanilang simbahan, isaalang-alang ang pagbibigay sa kanila ng maliit na regalo upang ipakita ang iyong suporta o tulungan silang ipakalat ang balita. Maaari mo ring ipagdasal ang mga nasa ministeryo, humihiling kay Diyos na pagpalain ang kanilang mga pagsisikap. Tandaan, kahit ang maliliit na kilos ay may malaking epekto!",
            "godsLove": "Ang talatang ito ay magandang nagpapakita kung paano nais ni Diyos na alagaan natin ang isa't isa. Kapag sinabi ni Juan na ipadala ang iba sa paraang karapat-dapat kay Diyos, ipinapakita nito na pinahahalagahan ni Diyos ang ating mga relasyon at ang paraan ng ating pakikitungo sa isa't isa. Mahal tayo ni Diyos ng labis at hinihimok tayong ipakita ang pagmamahal na iyon sa ating mga aksyon. Nais Niya tayong maging mapagbigay, mabait, at sumusuporta, lalo na sa mga nagtatrabaho nang mabuti sa Kanyang pangalan. Sa ating mga araw-araw na pagsubok, makakahanap tayo ng kaaliwan sa kaalaman na si Diyos ay nakasuporta sa atin at nais na i-extend natin ang parehong suporta sa iba. Ang Kanyang pagmamahal ang nagtutulak sa atin upang maging pagpapala!",
            "reflection": "Paano mo maipapakita ang pagmamahal at suporta sa isang tao sa iyong buhay na nagsisilbi kay Diyos o sa iyong komunidad sa linggong ito?"
          }
        },
        "7": {
          "en": {
            "understanding": "In 3 John 1:7, the verse speaks about a group of believers who went out to share the message of Jesus. They ventured out not for personal gain but purely for the sake of spreading God's name. This reveals a powerful commitment to their faith, showing that their mission was to serve rather than to receive. Historically, during the time this letter was written, many Christians were traveling to share the gospel, often facing challenges and opposition. They chose to rely on God and their fellow believers instead of seeking help from non-believers, showing their dedication to their mission and trust in God’s provision.",
            "livingItOut": "To live out the message of this verse, think about ways you can serve others without expecting anything in return. For instance, you might volunteer at a local charity or help a neighbor in need. Consider giving your time or talents to a community project, such as teaching kids in your neighborhood or organizing a clean-up drive. It’s about being generous and supportive, just like those early believers. Even small acts, like offering encouragement to someone going through a tough time, can reflect the love of Jesus. Remember, it’s not always about money or resources; sometimes, your time and kindness are the best gifts.",
            "godsLove": "This verse beautifully illustrates God's love, showing how He sends people out to share His truth without expecting anything in return. Just like these believers, God asks us to trust Him to provide for our needs as we step out in faith. It's a reminder that God cares for us deeply; He wants us to be part of His mission in the world. When we give ourselves to serve others, we are reflecting His heart. In our everyday struggles, we can find comfort knowing that God is with us, guiding us to share His love and grace with those around us. He loves us enough to use us as vessels of His goodness.",
            "reflection": "What is one way you can serve someone today without expecting anything back?"
          },
          "tl": {
            "understanding": "Sa 3 Juan 1:7, sinasabi ng talatang ito na may grupo ng mga mananampalataya na umalis para ipahayag ang mensahe ni Jesus. Pumunta sila hindi para sa sariling kapakinabangan kundi para sa ikakalat ng pangalan ng Diyos. Ipinapakita nito ang kanilang matinding dedikasyon sa pananampalataya, na ang kanilang misyon ay maglingkod at hindi tumanggap. Sa panahon ng sulat na ito, maraming Kristiyano ang naglalakbay upang ipahayag ang ebanghelyo, madalas na humaharap sa mga hamon at pagtutol. Pinili nilang umasa sa Diyos at sa kanilang kapwa mananampalataya sa halip na humingi ng tulong sa mga hindi mananampalataya, na nagpapakita ng kanilang pagtitiwala sa misyon at sa pagbibigay ng Diyos.",
            "livingItOut": "Para maisakatuparan ang mensahe ng talatang ito, isipin mo kung paano ka makapaglilingkod sa iba nang walang inaasahang kapalit. Halimbawa, puwede kang mag-volunteer sa isang lokal na charity o tumulong sa kapitbahay na nangangailangan. Isaalang-alang ang pagbibigay ng iyong oras o talento sa isang proyekto sa komunidad, tulad ng pagtuturo sa mga bata sa iyong lugar o pag-organisa ng clean-up drive. Mahalaga ang pagiging mapagbigay at sumusuporta, tulad ng mga unang mananampalataya. Kahit ang maliliit na gawa, tulad ng pagbibigay ng suporta sa isang tao na dumadaan sa mahirap na sitwasyon, ay maaaring magpakita ng pagmamahal ni Jesus. Tandaan, hindi lang ito tungkol sa pera o yaman; minsan, ang iyong oras at kabaitan ang pinakamagandang regalo.",
            "godsLove": "Ang talatang ito ay magandang nagpapakita ng pagmamahal ng Diyos, na ipinapakita kung paano Siya nagpapadala ng mga tao upang ipahayag ang Kanyang katotohanan nang walang inaasahan. Katulad ng mga mananampalatayang ito, hinihiling ng Diyos na magtiwala tayo sa Kanya na Siya ang magbibigay ng ating mga pangangailangan habang tayo ay lumalakad sa pananampalataya. Isang paalala na ang Diyos ay may malalim na malasakit sa atin; nais Niya tayong maging bahagi ng Kanyang misyon sa mundo. Kapag tayo ay naglilingkod sa iba, naipapakita natin ang Kanyang puso. Sa ating pang-araw-araw na laban, makakahanap tayo ng kapanatagan sa kaalaman na ang Diyos ay kasama natin, ginagabayan tayo upang ibahagi ang Kanyang pagmamahal at biyaya sa mga tao sa paligid natin. Mahal na mahal Niya tayo at nais tayong gamitin bilang mga daluyan ng Kanyang kabutihan.",
            "reflection": "Ano ang isang paraan na maari mong paglingkuran ang isang tao ngayong araw nang walang inaasahang kapalit?"
          }
        },
        "8": {
          "en": {
            "understanding": "In this verse, John is encouraging the believers to support those who are spreading the truth of the Gospel. He emphasizes the importance of partnership in ministry. When we help those who are dedicated to sharing God's message, we become co-workers in spreading His truth. This isn't just about financial support; it’s about encouraging and praying for them as well. John highlights that by supporting these workers, we participate in God's mission and share in the joy of seeing lives changed by the Gospel.",
            "livingItOut": "To live this verse out today, think of ways you can support those who are working hard to share God's love and truth. This could mean volunteering your time at your local church, donating to a mission project, or simply encouraging a friend who is involved in ministry. For example, if you know someone who is a pastor or a missionary, send them a message of encouragement or pray for their work. You can also support local charities that help those in need, showing that you care about the truth and love of God being shared in your community.",
            "godsLove": "This verse beautifully shows God's love for us by reminding us of our role in His grand story. He invites us to be part of something bigger—His mission to share truth and love with others. When we support those who are spreading His message, we are reflecting God's heart for people. It’s like a loving father who wants all His children to be part of the family business, sharing joy and hope with others. No matter where we are in life, we can always contribute to this mission, feeling His presence in our actions.",
            "reflection": "Who can you support today in sharing God's truth and love?"
          },
          "tl": {
            "understanding": "Sa talatang ito, hinihikayat ni Juan ang mga mananampalataya na suportahan ang mga taong nagdadala ng katotohanan ng Ebanghelyo. Binibigyang-diin niya ang kahalagahan ng pakikipagtulungan sa ministeryo. Kapag tinutulungan natin ang mga dedikado sa pagbabahagi ng mensahe ng Diyos, nagiging katuwang tayo sa pagpapalaganap ng Kanyang katotohanan. Hindi lang ito tungkol sa pinansyal na suporta; tungkol din ito sa pagbibigay ng lakas ng loob at panalangin para sa kanila. Ipinapakita ni Juan na sa pagsuporta sa mga manggagawa, nakikilahok tayo sa misyon ng Diyos at nakikibahagi sa kagalakan ng pagbabago ng buhay dahil sa Ebanghelyo.",
            "livingItOut": "Para isabuhay ang talatang ito ngayon, isipin mo kung paano ka makakatulong sa mga nagtatrabaho para ipakalat ang pag-ibig at katotohanan ng Diyos. Maaaring magboluntaryo ka sa iyong lokal na simbahan, magdonate sa isang proyekto ng misyon, o simpleng magbigay ng lakas ng loob sa isang kaibigang kasangkot sa ministeryo. Halimbawa, kung may kakilala kang pastor o misyonaryo, magpadala ka sa kanila ng mensahe ng suporta o ipanalangin ang kanilang gawain. Maaari ka ring sumuporta sa mga lokal na charity na tumutulong sa mga nangangailangan, na nagpapakita na mahalaga sa iyo ang pagdadala ng katotohanan at pag-ibig ng Diyos sa iyong komunidad.",
            "godsLove": "Ang talatang ito ay nagpapakita ng pag-ibig ng Diyos para sa atin sa pamamagitan ng paalala sa atin ng ating papel sa Kanyang dakilang kwento. Inaanyayahan tayo Niya na maging bahagi ng isang mas malaking misyon—ang ibahagi ang katotohanan at pag-ibig sa iba. Kapag sinusuportahan natin ang mga nagdadala ng Kanyang mensahe, pinapakita natin ang puso ng Diyos para sa mga tao. Parang isang mapagmahal na ama na gustong makasama ang lahat ng Kanyang anak sa pamilya, ibinabahagi ang saya at pag-asa sa iba. Anuman ang ating kalagayan sa buhay, palagi tayong makakapag-ambag sa misyong ito, nararamdaman ang Kanyang presensya sa ating mga aksyon.",
            "reflection": "Sino ang maaari mong suportahan ngayon sa pagbabahagi ng katotohanan at pag-ibig ng Diyos?"
          }
        },
        "9": {
          "en": {
            "understanding": "In this verse, John is expressing his concern about a leader in the church named Diotrephes. John had previously written to the church about important matters, but Diotrephes, who was very proud and wanted to be in charge, was not listening to him. This shows us that Diotrephes valued his own authority over the unity and teachings of the church. His behavior caused division, as he even rejected teachers sent by John and tried to kick out anyone who disagreed with him. This situation highlights the dangers of pride and the importance of listening to wise counsel within the church community.",
            "livingItOut": "To apply this verse in our daily lives, we need to be aware of our own pride and desire for control. Instead of trying to be the 'boss' in our relationships or communities, we should practice humility and be open to others' ideas and teachings. For example, if you’re in a group project at work or school, instead of insisting on your way, try to listen to what others have to say and work together. Encourage open discussions in your family or friends' circle, making sure everyone feels heard. This will foster a spirit of cooperation and love, just like how a healthy church should function.",
            "godsLove": "This verse reminds us that God values humility and community over pride and self-importance. Even when we face leaders or situations that seem divisive, God’s love encourages us to seek unity and understanding. He is like a loving father who wants His children to get along and support one another, rather than compete for attention. When we feel overshadowed by others’ pride, we can find comfort in knowing that God sees our hearts and our struggles. His grace is always there to help us choose love and unity, even in challenging situations.",
            "reflection": "How can you practice humility in your relationships this week?"
          },
          "tl": {
            "understanding": "Sa talatang ito, ipinapahayag ni Juan ang kanyang pag-aalala tungkol sa isang lider sa simbahan na si Diotrephes. Nagsulat na si Juan sa simbahan tungkol sa mga mahahalagang bagay, pero si Diotrephes, na puno ng kayabangan at gustong manguna, ay hindi siya pinapansin. Ipinapakita nito na mas pinahalagahan ni Diotrephes ang kanyang sariling kapangyarihan kaysa sa pagkakaisa at mga turo ng simbahan. Ang kanyang asal ay nagdulot ng hidwaan, dahil hindi lang niya tinanggihan ang mga guro na ipinadala ni Juan kundi sinubukan din niyang paalisin ang sinumang hindi sumasang-ayon sa kanya. Itinataas nito ang mga panganib ng kayabangan at ang kahalagahan ng pakikinig sa matalinong payo sa loob ng simbahan.",
            "livingItOut": "Para maipakita ang talatang ito sa ating pang-araw-araw na buhay, kailangan nating maging aware sa ating sariling kayabangan at pagnanais na kontrolin ang mga bagay. Sa halip na magpanggap na 'boss' sa ating mga relasyon o komunidad, dapat tayong magpraktis ng kababaang-loob at maging bukas sa mga ideya at turo ng iba. Halimbawa, kung ikaw ay nasa isang grupo sa trabaho o paaralan, imbes na ipilit ang iyong paraan, subukan mong makinig sa mga sinasabi ng iba at magtulungan. Hikayatin ang mga open discussions sa iyong pamilya o grupo ng kaibigan, siguraduhing naririnig ang lahat. Makakatulong ito sa pagkakaroon ng diwa ng kooperasyon at pagmamahal, katulad ng dapat na mangyari sa isang malusog na simbahan.",
            "godsLove": "Ang talatang ito ay nagpapaalala sa atin na pinahahalagahan ng Diyos ang kababaang-loob at pagkakaisa higit pa sa kayabangan at pansariling interes. Kahit na nahaharap tayo sa mga lider o sitwasyon na tila nagdudulot ng hidwaan, ang pagmamahal ng Diyos ay nag-uudyok sa atin na maghanap ng pagkakaisa at pag-unawa. Siya ay parang isang mapagmahal na Ama na nais na magkaisa at suportahan ng Kanyang mga anak ang isa't isa, sa halip na makipagkumpitensya para sa atensyon. Kapag tayo ay nadarama na na-ooverwhelm ng kayabangan ng iba, makakahanap tayo ng kapanatagan sa kaalaman na nakikita ng Diyos ang ating mga puso at mga paghihirap. Ang Kanyang biyaya ay laging naririyan upang tulungan tayong pumili ng pagmamahal at pagkakaisa, kahit sa mga hamon.",
            "reflection": "Paano mo maipapakita ang kababaang-loob sa iyong mga relasyon ngayong linggo?"
          }
        },
        "10": {
          "en": {
            "understanding": "In this verse, the Apostle John points out a serious issue in the church. A man named Diotrephes is spreading lies about John and the other believers, which causes division and conflict. Instead of supporting his fellow Christians, he is turning them away and even kicking some out of the church. This behavior is harmful not only to the unity of the church but also to the spiritual well-being of its members. John emphasizes the importance of welcoming fellow believers and working together in love, rather than allowing pride and falsehood to create barriers among them. This teaches us about the significance of community and the dangers of gossip and selfishness in our relationships.",
            "livingItOut": "To live out this verse, we can start by being mindful of how we speak about others, especially in our community or church. Instead of spreading rumors or negative comments, let’s choose to uplift and support our fellow believers. For example, if you hear someone talking negatively about another person, you can gently redirect the conversation or speak positively about that person. Additionally, make an effort to welcome others into your circles, whether it's inviting someone new to your Bible study or reaching out to those who may feel left out. This act of kindness can help build a strong, loving community where everyone feels valued and included.",
            "godsLove": "This verse shows us how much God cares about unity and love among His people. Just like a loving father, God wants us to support one another and live in harmony. When we face conflicts or hear negative things about others, we can remember that God calls us to act with love and grace. He understands our struggles and encourages us to choose kindness over hostility. By showing love and acceptance to others, we reflect God's character and His desire for us to be a family in faith. No matter what challenges we face, we can trust that God is always there to support us and guide us in building a loving community.",
            "reflection": "How can you actively contribute to fostering a spirit of unity and encouragement within your community this week?"
          },
          "tl": {
            "understanding": "Sa talatang ito, itinuturo ni Apostol Juan ang isang seryosong isyu sa simbahan. Isang tao na si Diotrephes ang nagkalat ng mga kasinungalingan tungkol kay Juan at sa ibang mananampalataya, na nagdudulot ng hidwaan at alitan. Sa halip na suportahan ang kanyang mga kapwa Kristiyano, tinatanggihan niya ang mga ito at pinalalayas pa ang ilan mula sa simbahan. Ang ganitong asal ay nakasasama hindi lamang sa pagkakaisa ng simbahan kundi pati na rin sa espiritwal na kalagayan ng mga miyembro nito. Binibigyang-diin ni Juan ang kahalagahan ng pagtanggap sa kapwa mananampalataya at ang pakikipagtulungan sa pagmamahal, sa halip na payagan ang kayabangan at kasinungalingan na lumikha ng hadlang sa kanilang samahan. Itinuro nito sa atin ang kahalagahan ng komunidad at ang mga panganib ng tsismis at pagiging makasarili sa ating mga relasyon.",
            "livingItOut": "Para maisakatuparan ang talatang ito, maaari tayong maging mapanuri sa ating mga sinasabi tungkol sa iba, lalo na sa ating komunidad o simbahan. Sa halip na kumalat ng mga tsismis o negatibong komento, piliin nating itaas at suportahan ang ating mga kapwa mananampalataya. Halimbawa, kung may marinig kang tao na nagkakalat ng negatibong salita tungkol sa iba, maaari mong dahan-dahang ilihis ang usapan o magsalita ng mabuti tungkol sa taong iyon. Bukod dito, maglaan ng oras upang tanggapin ang iba sa iyong mga bilog, kahit na ito ay ang pag-anyaya sa bagong tao sa iyong Bible study o pag-abot sa mga maaaring makaramdam ng pagkaalis. Ang ganitong kilos ng kabaitan ay makakatulong sa pagbuo ng isang matatag at mapagmahal na komunidad kung saan ang lahat ay nararamdaman na mahalaga at kasama.",
            "godsLove": "Ipinapakita ng talatang ito kung gaano kalaga sa Diyos ang pagkakaisa at pagmamahal sa Kanyang mga tao. Tulad ng isang mapagmahal na ama, nais ng Diyos na suportahan natin ang isa't isa at mamuhay sa pagkakasundo. Kapag tayo ay humaharap sa mga alitan o naririnig ang negatibong mga bagay tungkol sa iba, maaari nating tandaan na tinatawag tayo ng Diyos na kumilos nang may pagmamahal at biyaya. Nauunawaan Niya ang ating mga pakik struggles at hinihimok tayo na pumili ng kabaitan sa halip na galit. Sa pamamagitan ng pagpapakita ng pagmamahal at pagtanggap sa iba, naisasalamin natin ang pagkatao ng Diyos at ang Kanyang hangarin para sa atin na maging isang pamilya sa pananampalataya. Sa kabila ng mga pagsubok na ating hinaharap, maaari tayong magtiwala na laging nandiyan ang Diyos upang suportahan tayo at gabayan tayo sa pagbubuo ng isang mapagmahal na komunidad.",
            "reflection": "Paano ka makakatulong sa pagbubuo ng diwa ng pagkakaisa at paghikayat sa iyong komunidad sa linggong ito?"
          }
        },
        "11": {
          "en": {
            "understanding": "In 3 John 1:11, the Apostle John is reminding us to choose good over evil. He contrasts the behavior of two types of people: those who do good and those who do evil. John specifically calls out Diotrephes, who acted selfishly and refused to accept the teachings of Jesus, showing that he was not truly following God. This verse encourages us to reflect on our own actions and ensure that we are living in a way that aligns with God's teachings. The message is clear: we should strive to imitate good behavior, which reflects God's character, rather than following the path of evil that leads us away from Him.",
            "livingItOut": "To live out this verse, start by examining your relationships and the influences around you. Ask yourself, are there people in your life whose actions lead you away from doing good? Surround yourself with friends and mentors who inspire you to be better and do good. Practice kindness in small ways, like helping a neighbor, volunteering in your community, or simply being a good listener to someone who needs to talk. Every day, choose to act with love and integrity, even when it’s hard. For example, instead of gossiping about a friend, choose to encourage them or speak well of them. These small choices reflect the goodness that God desires from us.",
            "godsLove": "This verse beautifully shows God's love for us by encouraging us to choose goodness, which comes from knowing Him. God wants us to reflect His love in our actions, and He provides us with the strength to do good. When we choose to live according to His ways, we experience His presence in our lives. It’s like a loving parent guiding a child, wanting them to grow up to be kind and compassionate. Even when we struggle to make the right choices, God is there to lift us up and remind us of the goodness He has for us. His heart is full of grace, inviting us to turn away from evil and embrace the good He offers every day.",
            "reflection": "What is one small way you can choose to do good today, even when it feels easier to follow the crowd?"
          },
          "tl": {
            "understanding": "Sa 3 Juan 1:11, pinapaalala sa atin ni Apostol Juan na piliin ang kabutihan kaysa kasamaan. Ikinukumpara niya ang ugali ng dalawang klase ng tao: ang gumagawa ng mabuti at ang gumagawa ng masama. Tinutukoy ni Juan si Diotrephes na may masamang asal at hindi tumanggap sa mga turo ni Jesus, na nagpapakita na hindi siya tunay na sumusunod sa Diyos. Ang talatang ito ay nagtuturo sa atin na pag-isipan ang ating mga aksyon at tiyakin na ang ating pamumuhay ay ayon sa mga turo ng Diyos. Malinaw ang mensahe: dapat tayong magsikap na gayahin ang mabuting asal na nagpapakita ng katangian ng Diyos, sa halip na sumunod sa masamang landas na nagdadala sa atin palayo sa Kanya.",
            "livingItOut": "Para maisakatuparan ang talatang ito, simulan mong suriin ang iyong mga relasyon at mga impluwensya sa paligid mo. Tanungin ang sarili, may mga tao ba sa buhay mo na ang mga aksyon ay nagdadala sa iyo palayo sa paggawa ng mabuti? Palibutan ang sarili ng mga kaibigan at mentor na nag-uudyok sa iyo na maging mas mabuti. Magpraktis ng kabaitan sa maliliit na paraan, tulad ng pagtulong sa kapitbahay, pag-volunteer sa komunidad, o simpleng pag-aalok ng pakikinig sa isang taong kailangang makipag-usap. Sa bawat araw, piliin ang kumilos nang may pagmamahal at integridad, kahit na mahirap. Halimbawa, sa halip na makialam sa chismis tungkol sa isang kaibigan, piliin na hikayatin siya o magsalita ng mabuti tungkol sa kanya. Ang mga maliliit na pagpili na ito ay nagpapakita ng kabutihan na nais ng Diyos mula sa atin.",
            "godsLove": "Ang talatang ito ay maganda ang pagpapakita ng pagmamahal ng Diyos sa atin sa pamamagitan ng paghikayat na pumili ng kabutihan, na nagmumula sa pagkilala sa Kanya. Nais ng Diyos na ipakita natin ang Kanyang pagmamahal sa ating mga aksyon, at binibigyan Niya tayo ng lakas na gumawa ng mabuti. Kapag pinili nating mamuhay ayon sa Kanyang mga daan, nararanasan natin ang Kanyang presensya sa ating buhay. Para itong isang mapagmahal na magulang na ginagabayan ang anak, nais silang lumaki na mabait at mahabagin. Kahit na nahihirapan tayong gumawa ng tamang desisyon, nariyan ang Diyos upang itaas tayo at ipaalala ang kabutihang Kanyang inaalok. Puno ng biyaya ang Kanyang puso, iniimbitahan tayong iwanan ang masama at yakapin ang kabutihan na Kanyang inaalok araw-araw.",
            "reflection": "Ano ang isang maliit na paraan na maaari mong piliing gumawa ng mabuti ngayon, kahit na mas madali itong sumunod sa agos?"
          }
        },
        "12": {
          "en": {
            "understanding": "In this verse, John is highlighting Demetrius as a person who has earned a good reputation. Unlike Diotrephes, who was causing problems in the church, Demetrius is someone who knows the truth and lives it out. John’s mention of Demetrius at the end of the letter indicates that he likely carried this message to Gaius. This was important because John wanted to show that they could trust Demetrius, especially when false teachers were trying to lead people astray. By affirming Demetrius's character, John is also affirming his own role as a trustworthy leader in the church, ensuring that the truth remains strong among believers.",
            "livingItOut": "To live out this verse today, think about the people in your life who embody good character and integrity, just like Demetrius. Maybe you can encourage someone who is doing well, whether at work, in school, or in your community. Consider writing a note or giving a compliment to someone who deserves recognition for their honesty and dedication. You can also reflect on your own actions: are you living in a way that others can look up to? Strive to be a person known for your good testimony, and share the truth of God’s love in your daily interactions.",
            "godsLove": "This verse shows us how much God values integrity and truthfulness. Just like Demetrius, God wants us to live in a way that reflects His love and character. When we walk in truth, we not only honor God, but we also inspire others to do the same. God cares deeply about how we treat one another and encourages us to support those who are striving to do good. Remember that even when faced with challenges or false teachings, God is there to guide and support you. He loves you and desires for you to be surrounded by others who uplift and encourage you.",
            "reflection": "Who in your life deserves a good word of encouragement for their character and faithfulness?"
          },
          "tl": {
            "understanding": "Sa talatang ito, binibigyang-diin ni Juan si Demetrius bilang isang tao na may magandang reputasyon. Kabaligtaran siya ni Diotrephes, na nagdudulot ng problema sa simbahan; si Demetrius ay kilala sa katotohanan at namumuhay dito. Ang pagbanggit ni Juan kay Demetrius sa dulo ng sulat ay nagpapakita na siya ang posibleng nagdala ng mensahe kay Gaius. Mahalaga ito dahil nais ni Juan na ipakita na maaasahan si Demetrius, lalo na sa panahon ng mga maling guro na nagtatangkang iligaw ang mga tao. Sa pag-affirm kay Demetrius, pinatutunayan din ni Juan ang kanyang sarili bilang isang mapagkakatiwalaang lider sa simbahan, na tinitiyak na mananatiling matatag ang katotohanan sa mga mananampalataya.",
            "livingItOut": "Para maisakatuparan ang talatang ito sa araw-araw, isipin ang mga tao sa buhay mo na may magandang karakter at integridad, gaya ni Demetrius. Maari kang magbigay ng suporta sa isang tao na nagtatrabaho ng mabuti, maging sa trabaho, paaralan, o sa komunidad. Isipin mong magsulat ng note o magbigay ng papuri sa isang tao na nararapat sa pagkilala dahil sa kanilang katapatan at dedikasyon. Maaari mo ring suriin ang iyong sariling mga kilos: namumuhay ka ba sa paraang maaaring tularan ng iba? Sikaping maging isang tao na kilala sa iyong magandang testimonya, at ibahagi ang katotohanan ng pagmamahal ng Diyos sa iyong pang-araw-araw na pakikisalamuha.",
            "godsLove": "Ipinapakita ng talatang ito kung gaano kahalaga sa Diyos ang integridad at katotohanan. Tulad ni Demetrius, nais ng Diyos na mamuhay tayo sa paraang sumasalamin sa Kanyang pagmamahal at karakter. Kapag tayo ay namumuhay sa katotohanan, hindi lamang natin pinapahalagahan ang Diyos, kundi pinasisigla din natin ang iba na gawin ang parehong. Mahalaga sa Diyos kung paano natin tratuhin ang isa’t isa at hinihimok tayo na suportahan ang mga nagsusumikap na gumawa ng mabuti. Tandaan na kahit na nahaharap sa mga hamon o maling mga aral, naroroon ang Diyos upang gabayan at suportahan ka. Mahal ka Niya at nagnanais na mapalibutan ka ng mga tao na nagtataas at nagbibigay ng inspirasyon sa iyo.",
            "reflection": "Sino sa buhay mo ang karapat-dapat bigyan ng magandang salita ng pasasalamat para sa kanilang karakter at katapatan?"
          }
        },
        "13": {
          "en": {
            "understanding": "In this verse, John expresses that he has a lot to say but prefers to talk face-to-face rather than through written words. During John's time, letters were written using a reed and ink, which made communication more personal when done in person. John values the connection and intimacy of direct communication over the limitations of writing. This shows us that while letters are important, nothing beats the warmth of a real conversation where you can see and feel the other person's presence. John’s desire to connect personally also highlights the importance of relationships in our spiritual lives.",
            "livingItOut": "To live out this verse today, think about the relationships in your life. Are there people you haven’t connected with in a while? Instead of just sending a text or an email, consider picking up the phone or meeting them in person. For example, if you have a friend or family member who is going through a tough time, a simple visit or a heartfelt conversation can mean so much more than just a written message. Make a plan this week to reach out and have a genuine conversation with someone you care about. This can strengthen your bond and make both of you feel more valued.",
            "godsLove": "This verse reminds us of how God desires a personal relationship with us. Just like John wants to connect with his friends in a deeper way, God wants to connect with us beyond just words on a page. He cares about our hearts and our struggles, and He longs to have direct conversations with us through prayer and worship. God's love is about intimacy and connection, showing us that He is always there, ready to listen and respond. When we take the time to talk to Him, we experience His care and guidance in our everyday lives, reassuring us that we are never alone.",
            "reflection": "Who is someone in your life that you need to connect with more personally this week?"
          },
          "tl": {
            "understanding": "Sa talatang ito, sinasabi ni Juan na marami siyang nais ipahayag pero mas gusto niyang makipag-usap nang personal kaysa sa pamamagitan ng sulat. Noong panahon ni Juan, ang pagsusulat ay gamit ang reed at tinta, kaya mas mahalaga ang personal na koneksyon kaysa sa nakasulat na salita. Pinapakita nito na kahit mahalaga ang mga sulat, walang tatalo sa init ng tunay na pag-uusap kung saan makikita at mararamdaman mo ang presensya ng kausap. Ang pagnanais ni Juan na makipag-ugnayan ng personal ay nagbibigay-diin sa kahalagahan ng mga relasyon sa ating buhay espiritual.",
            "livingItOut": "Para maisakatuparan ang talatang ito sa buhay, isipin mo ang mga tao sa paligid mo. May mga kaibigan ka bang hindi mo nakakausap nang matagal? Imbis na mag-text o mag-email, subukan mong tawagan sila o makipagkita nang personal. Halimbawa, kung may kaibigan o kapamilya kang dumadaan sa mahirap na sitwasyon, mas magiging makabuluhan ang isang bisita o taos-pusong pag-uusap kaysa sa isang mensahe lang. Magplano ka ngayong linggo na makipag-ugnayan at magkaroon ng tunay na pag-uusap sa isang taong mahalaga sa'yo. Makakatulong ito sa pagpapalakas ng inyong ugnayan at parehong makadarama ng halaga.",
            "godsLove": "Ang talatang ito ay nagpapaalala sa atin na nais ng Diyos ng personal na relasyon sa atin. Gaya ng pagnanais ni Juan na kumonekta sa kanyang mga kaibigan sa mas malalim na paraan, nais ng Diyos na makipag-usap sa atin hindi lang sa pamamagitan ng mga salita sa pahina. Mahalaga ang ating puso at mga pinagdadaanan, at sabik siyang makipag-usap sa atin sa pamamagitan ng panalangin at pagsamba. Ang pag-ibig ng Diyos ay tungkol sa pagiging malapit at konektado, na nagpapakita na palagi siyang nandiyan, handang makinig at tumugon. Kapag naglaan tayo ng oras upang kausapin siya, nararanasan natin ang kanyang pag-aalaga at gabay sa ating araw-araw na buhay, na nagpapaalala sa atin na hindi tayo nag-iisa.",
            "reflection": "Sino ang isang tao sa buhay mo na kailangan mong makipag-ugnayan nang mas personal ngayong linggo?"
          }
        },
        "14": {
          "en": {
            "understanding": "In this verse, John expresses his desire to meet his friends in person, rather than just communicating through letters. The phrase 'face to face' emphasizes the importance of personal connection and relationship, showing that John values being with his friends and sharing life together. In biblical times, letters were the primary way to stay in touch, but nothing could replace the warmth of a personal encounter. John also extends peace and greetings from mutual friends, indicating a strong community bond among believers. This verse highlights the significance of fellowship and love in the Christian life.",
            "livingItOut": "To live out this verse, think about people in your life that you haven’t seen for a while. Maybe it’s a family member, a friend, or a fellow church member. Take the initiative to reach out and plan a face-to-face meeting, whether it’s over coffee, a meal, or simply a visit to their home. You could also send a personal message of encouragement to someone who may need it. In our busy lives, we often rely on texts and social media, but take a moment to foster real connections. This could strengthen your relationships and bring joy to both you and those around you.",
            "godsLove": "This verse beautifully shows God’s love for us through the importance of relationships. Just as John wants to connect personally with his friends, God desires the same intimate connection with us. He is always present and ready to listen, offering us peace and comfort. God understands the value of community, and He surrounds us with friends and loved ones to encourage us in our journey. Even when we feel alone or distant, God is there, inviting us to draw near to Him and to one another, reminding us that we are never truly alone in this life.",
            "reflection": "Who is someone you can reach out to this week for a face-to-face conversation?"
          },
          "tl": {
            "understanding": "Sa talatang ito, ipinapahayag ni Juan ang kanyang pagnanais na makasama ang kanyang mga kaibigan sa personal, imbis na makipag-ugnayan lamang sa pamamagitan ng mga sulat. Ang pariral na 'face to face' ay nagpapakita ng halaga ng personal na koneksyon at relasyon, na nagpapakita na pinahahalagahan ni Juan ang pakikisama at pagbabahagi ng buhay kasama ang kanyang mga kaibigan. Sa mga panahon ng Bibliya, ang mga liham ang pangunahing paraan ng pakikipag-ugnayan, ngunit wala nang makakapantay sa init ng isang personal na pagkikita. Nagpapadala rin si Juan ng kapayapaan at bati mula sa mga kaibigan, na nagpapahiwatig ng matibay na ugnayan sa komunidad ng mga mananampalataya. Ipinapakita ng talatang ito ang kahalagahan ng pagsasama at pagmamahal sa buhay Kristiyano.",
            "livingItOut": "Para maisakatuparan ang talatang ito, isipin ang mga tao sa iyong buhay na hindi mo pa nakikita nang matagal. Maaaring ito ay miyembro ng pamilya, kaibigan, o kasamahan sa simbahan. Maglaan ng panahon upang makipag-ugnayan at magplano ng personal na pagkikita, kahit na ito ay sa kape, pagkain, o simpleng pagbisita sa kanilang tahanan. Maaari ka ring magpadala ng personal na mensahe ng pampatibay-loob sa isang tao na maaaring mangailangan nito. Sa ating abalang buhay, madalas tayong umaasa sa mga text at social media, pero maglaan tayo ng oras para sa tunay na koneksyon. Makakatulong ito sa pagpapalakas ng ating mga relasyon at magdadala ng saya sa atin at sa mga tao sa paligid natin.",
            "godsLove": "Ang talatang ito ay maganda ang pagkakapakita ng pagmamahal ng Diyos sa atin sa pamamagitan ng kahalagahan ng mga relasyon. Tulad ng pagnanais ni Juan na kumonekta ng personal sa kanyang mga kaibigan, ang Diyos ay may ganitong pagnanasa na magkaroon ng malapit na koneksyon sa atin. Lagi siyang nandiyan, handang makinig, at nagbibigay sa atin ng kapayapaan at kaaliwan. Nauunawaan ng Diyos ang halaga ng komunidad, at pinaliligiran tayo ng mga kaibigan at mahal sa buhay upang hikayatin tayo sa ating paglalakbay. Kahit na sa mga pagkakataong pakiramdam natin ay nag-iisa o malayo, andiyan ang Diyos, inaanyayahan tayong lumapit sa Kanya at sa isa’t isa, at pinapaalalahanan tayong hindi tayo nag-iisa sa buhay na ito.",
            "reflection": "Sino ang isang tao na maaari mong kontakin ngayong linggo para sa isang personal na pag-uusap?"
          }
        }
      }
    }
  },
  "book": "3JN"
};
})();
