plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Volumes/Wotg Drive Mike/GitHub/Go-Mission/standalone-messenger-site"
publishOrigin = "config"
base = "/Volumes/Wotg Drive Mike/GitHub/Go-Mission/standalone-messenger-site"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]